# Generated by Django 2.2.7 on 2020-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='context1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='context2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='context3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='header1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='journal',
            name='header2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='header3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
